---
- name: "Gather facts demo"
  hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: "Show system results"
      debug:
        msg:  " {{ ansible_all_ipv4_addresses.0 }}"  
    