---
- name: "yum module demo"
  hosts: localhost
  vars:
    package: "net-tools.x86_64"
  become: true
  tasks:
    - name: "Install {{ package }} in servers"
      yum:
        name: " {{ package }} "
        state: present
      register: result
    - name: Debug message
      debug:
        var: "{{ result }}"
